[build]
builder = "nixpacks"
nixpacksPlan = """
[phases.setup]
nixPkgs = ['python39', 'gcc']
"""

[deploy]
startCommand = "python simple_start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
